name: Call Workflow which uses a Secret

on: 
  workflow_dispatch:

jobs:

  Call-Workflow:
    uses: MarkTopping/gha-reusable-wf-with-oidc/.github/workflows/demo-secret-inputs.yml@main
    secrets:
      # This secret must be passed into the called workflow.
      # This applies even though the Called Workflow Repo contains a secret called MY_SECRET (which goes unused) 
      MY_SECRET: "No you're not Batman; I am!"
  
