name: Demo - Auth then leverage

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:

  Caller-Hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello from Caller WF

  Call-Auth-WF:
    uses: mt-github-testing/privileged-automation/.github/workflows/auth.yml@main
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
  Test-If-Still-Authenticated:
    needs: Call-Auth-WF
    runs-on: ubuntu-latest
    steps:
      - name: 'Run Azure CLI command'
        run: |
          az account show
          pwd
